import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Web3Provider } from '@/components/Web3Provider';
import { AuthButton } from '@/components/AuthButton';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Web3Provider>
					<div className="min-h-screen flex flex-col">
						<header className="bg-white shadow-sm border-b">
							<div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
								<div className="flex justify-between items-center h-16">
									<h1 className="text-xl font-bold text-gray-900">
										Binder
									</h1>
									<AuthButton />
								</div>
							</div>
						</header>
						<main className="flex-1">{children}</main>
					</div>
				</Web3Provider>
			</body>
		</html>
	);
}
